#!/bin/bash

echo "📋 Instructions to check storage.ts on remote machine"
echo "===================================================="
echo ""
echo "Run these commands after SSH into remote machine:"
echo ""
echo "ssh abpwrk1@inlnqw1502"
echo "# Password: Unix11!"
echo ""
echo "cd \$HOME/dk/arc_studio"
echo ""
echo "# Check if the problematic SQL syntax exists:"
echo "grep -n 'sql<string | null>' server/storage.ts"
echo ""
echo "# If it returns results, the fix hasn't been applied"
echo "# Check specific methods:"
echo ""
echo "# Check updateUser method:"
echo "grep -A 15 'async updateUser' server/storage.ts | grep -E 'returning|autoX'"
echo ""
echo "# Check getAllUsersWithRoles:"
echo "grep -A 15 'async getAllUsersWithRoles' server/storage.ts | grep -E 'select|autoX'"
echo ""
echo "# Check the file modification time:"
echo "ls -la server/storage.ts"
echo ""
echo "# If fix is NOT applied, apply it manually:"
echo "echo '=== Manual Fix Instructions ==='"
echo ""
echo "# 1. Backup current file:"
echo "cp server/storage.ts server/storage.ts.backup-\$(date +%Y%m%d)"
echo ""
echo "# 2. Download the fixed version:"
echo "curl -o server/storage.ts https://raw.githubusercontent.com/dillipm021073/ApplicationInterfaceTracker/main/server/storage.ts"
echo ""
echo "# 3. Rebuild:"
echo "npm run build"
echo ""
echo "# 4. Restart application:"
echo "pm2 restart all  # or however the app is running"