#!/bin/bash

echo "🔍 Remote Error Investigation Commands"
echo "====================================="
echo ""
echo "After SSH to abpwrk1@inlnqw1502 (password: Unix11!)"
echo "Run these commands:"
echo ""
echo "cd \$HOME/dk/arc_studio"
echo ""
echo "# 1. Check console output for detailed errors:"
echo "# If running with PM2:"
echo "pm2 logs --err --lines 100 | grep -A5 -B5 'Failed to update user'"
echo ""
echo "# If running directly, check the console output or nohup.out:"
echo "tail -n 200 nohup.out 2>/dev/null | grep -A5 -B5 'Failed to update user'"
echo ""
echo "# 2. Enable detailed error logging temporarily:"
echo "cat > server/test-user-update.js << 'EOF'"
echo "require('dotenv').config();"
echo "const { DatabaseStorage } = require('./dist/server/storage.js');"
echo ""
echo "async function testUserUpdate() {"
echo "  const storage = new DatabaseStorage();"
echo "  "
echo "  try {"
echo "    console.log('Testing user update...');"
echo "    "
echo "    // First get user 5"
echo "    const user = await storage.getUser(5);"
echo "    console.log('Current user 5:', user);"
echo "    "
echo "    // Try to update"
echo "    const updated = await storage.updateUser(5, { role: 'admin' });"
echo "    console.log('Updated user:', updated);"
echo "  } catch (error) {"
echo "    console.error('Full error:', error);"
echo "    console.error('Error stack:', error.stack);"
echo "  }"
echo "  "
echo "  process.exit(0);"
echo "}"
echo ""
echo "testUserUpdate();"
echo "EOF"
echo ""
echo "node server/test-user-update.js"
echo ""
echo "# 3. Check database connection directly:"
echo "cat > test-direct-db.js << 'EOF'"
echo "const postgres = require('postgres');"
echo "const sql = postgres(process.env.DATABASE_URL || 'postgresql://env10o:OnlyForTest123@incetks154:5432/paaspg');"
echo ""
echo "async function test() {"
echo "  try {"
echo "    // Test simple query"
echo "    const users = await sql\`SELECT id, username, role FROM users WHERE id = 5\`;"
echo "    console.log('User query result:', users);"
echo "    "
echo "    // Test update"
echo "    const result = await sql\`"
echo "      UPDATE users SET role = role WHERE id = 5 RETURNING *"
echo "    \`;"
echo "    console.log('Update result:', result);"
echo "  } catch (err) {"
echo "    console.error('Database error:', err);"
echo "  } finally {"
echo "    await sql.end();"
echo "  }"
echo "}"
echo ""
echo "test();"
echo "EOF"
echo ""
echo "node test-direct-db.js"
echo ""
echo "# 4. Check TypeScript compilation:"
echo "cd server && npx tsc --noEmit storage.ts"